### ISSUE TITLE
Informational tasks

### ISSUE THREAD

**Issue by coder137** [schizelle/schizelle.github.io#4]
- [x] Update _gallery (put proper image name, title and subtitle)
- [x] Update _pages (be careful of indentation when putting html)
- [x] Update images and put proper names, make sure that if the names are changed you change it in all places in the site folder
- [x] Update logo.svg to a logo of your choice
- [x] Music clip embeds
- [x] Make sure images are not super high definition (it will slow down the website)
- [x] Make work videos aligned properly (they are currently all aligned on the left)
- [x] Put proper title for images
- [x] Resize images so that webpage loads faster

**Comment by coder137** [comment]
- [ ] Make work videos aligned properly (they are currently all aligned on the left)
- [ ] Put proper title to images
- [ ] Resize images so that webpage loads faster

**Comment by schizelle** [comment]
- [x] remove title from gallery conditionally
- [x] resume download pops up in a new tab
- [x] change background colour of the website https://www.thesitewizard.com/css/background-colour.shtml 
- [x] order the social buttons as gmail, insta, youtube (right side and bottom)
- [x] icon for the tab (rn it is like a world thing)
- [x] see my works button that leads to works
